"""
Internal MC test split from synthetic data generation.

Loads pre-rendered MC conversations from hist_synthetic_test.jsonl.
Each line already has the nanochat categorical eval format:
    {"messages": [{"role": "user", ...}, {"role": "assistant", ...}], "letters": ["A","B","C","D"]}

Generated by src/post_training/assemble.py (period-specific, held-out documents).
"""

import json
from tasks.common import Task


class InternalMC(Task):

    def __init__(self, data_file, **kwargs):
        super().__init__(**kwargs)
        with open(data_file, 'r', encoding='utf-8') as f:
            self.data = [json.loads(line) for line in f if line.strip()]

    @property
    def eval_type(self):
        return 'categorical'

    def num_examples(self):
        return len(self.data)

    def get_example(self, index):
        row = self.data[index]
        return {
            "messages": row["messages"],
            "letters": row["letters"],
        }

    def evaluate(self, conversation, assistant_response):
        assert assistant_response in conversation['letters']
        return assistant_response == conversation['messages'][-1]['content']
