#!/usr/bin/env bash
# Run the FOUR eval families over a set of yearly (vintage) models — one uniform loop.
#
# For each (year, test) cell it generates a tiny eval-only YAML that pins the year's
# base checkpoint via `checkpoint: {year: Y}` (the nanochat backend year-knob — no
# per-year file staging), selects the test's evaluator, and runs eval.py. Base-only
# tests (LAB + external benchmarks) run --no-adapter; policy/value additionally load
# that year's trained LoRA adapter.
#
# Same GPU job-pool + idempotency pattern as scripts/pod/eval_values_battery.sh.
#
# Usage:
#   TESTS="lab hellaswag winogrande piqa mmlu_history" \
#   YEARS="1931 1955 1975 1995 2015" \
#   bash scripts/run_families.sh
#
# Env:
#   YEARS            space-separated model years (default: all rows of the 23-year map)
#   TESTS            space-separated test names (default: lab + 4 external benchmarks)
#                    known: policy value lab arc hellaswag winogrande piqa mmlu_history
#   OUT_ROOT         POLICY_PRED_DATA_ROOT for outputs (default $HOME/pp_families)
#   JOBS_PER_GPU     parallel eval jobs per GPU (default 2)
#   ADAPTER_ROOT     dir of per-year adapters for policy/value (default $OUT_ROOT/experiments)
#   ADAPTER_PATTERN  printf pattern -> adapter experiment name (default policy_%d_nanochat_roll10_n10000)
#   EVAL_DATA        dir with lab_eval.jsonl etc (default D:/hist_LLM/eval_data)
#   HF_CACHE         HF datasets cache for hellaswag/etc (default $EVAL_DATA/hf_cache)
set -uo pipefail
cd "$(dirname "$0")/.." || exit 1   # repo root
[[ -d .venv ]] && source .venv/bin/activate 2>/dev/null || true

OUT_ROOT="${OUT_ROOT:-$HOME/pp_families}"
JOBS_PER_GPU="${JOBS_PER_GPU:-2}"
ADAPTER_ROOT="${ADAPTER_ROOT:-$OUT_ROOT/experiments}"
ADAPTER_PATTERN="${ADAPTER_PATTERN:-policy_%d_nanochat_roll10_n10000}"
EVAL_DATA="${EVAL_DATA:-D:/hist_LLM/eval_data}"
HF_CACHE="${HF_CACHE:-$EVAL_DATA/hf_cache}"
TESTS="${TESTS:-lab hellaswag winogrande piqa mmlu_history}"
YAML_DIR="experiments/families"
LOG_DIR="/tmp/families_eval_logs"
mkdir -p "$OUT_ROOT/experiments" "$YAML_DIR" "$LOG_DIR"

if [[ -z "${YEARS:-}" ]]; then
    YEARS=$(tail -n +2 scripts/pod/continuous_d23_rel20/year_step_map.csv | cut -d, -f1 | tr '\n' ' ')
fi

# policy/value probe the year's trained belief model (base + LoRA); the benchmarks
# measure the year's BASE capability/leakage (no adapter).
uses_adapter() { case "$1" in policy | value) return 0 ;; *) return 1 ;; esac; }

# Write the per-cell experiment YAML: common header + the test's eval: block.
write_yaml() {
    local name="$1" year="$2" test="$3" f="$YAML_DIR/$1.yaml"
    {
        echo "# auto-generated by run_families.sh (never committed)"
        echo "name: $name"
        echo "model_type: nanochat"
        echo "checkpoint: {year: $year}"
    } > "$f"
    case "$test" in
        policy) cat >> "$f" <<EOF
eval:
  evaluator: policy_battery_variants
  source: csv
  csv_path: us_policy_event_battery_v4.csv
  modes: [yes_no]
  rel_min: -20
  rel_max: 20
EOF
            ;;
        value) cat >> "$f" <<EOF
eval:
  evaluator: values_battery
  csv_path: us_values_battery_v1.csv
  chat_format: false
EOF
            ;;
        lab) cat >> "$f" <<EOF
eval:
  evaluator: nanochat_task
  task: lab
  data_file: $EVAL_DATA/lab_eval.jsonl
EOF
            ;;
        arc) cat >> "$f" <<EOF
eval:
  evaluator: nanochat_task
  task: arc
  subset: ARC-Challenge
  split: test
  cache_dir: $HF_CACHE
EOF
            ;;
        mmlu_history) cat >> "$f" <<EOF
eval:
  evaluator: nanochat_task
  task: mmlu_history
  split: test
EOF
            ;;
        hellaswag | winogrande | piqa) cat >> "$f" <<EOF
eval:
  evaluator: nanochat_task
  task: $test
  split: validation
  cache_dir: $HF_CACHE
EOF
            ;;
        *) echo "unknown test: $test" >&2; return 1 ;;
    esac
}

run_cell() {
    local gpu="$1" year="$2" test="$3"
    local name="fam_${year}_${test}"
    [[ -f "$OUT_ROOT/experiments/$name/eval.json" ]] && return 2   # already done
    write_yaml "$name" "$year" "$test" || return 3
    local args=(--experiment "$YAML_DIR/$name.yaml" --force)
    if uses_adapter "$test"; then
        # shellcheck disable=SC2059
        local adapter="$ADAPTER_ROOT/$(printf "$ADAPTER_PATTERN" "$year")/checkpoint"
        [[ -f "$adapter/adapter_config.json" ]] || { echo "no adapter: $adapter" > "$LOG_DIR/$name.log"; return 3; }
        args+=(--adapter "$adapter")
    else
        args+=(--no-adapter)
    fi
    POLICY_PRED_DATA_ROOT="$OUT_ROOT" CUDA_VISIBLE_DEVICES="$gpu" HF_HOME="$HF_CACHE" \
        python eval.py "${args[@]}" > "$LOG_DIR/$name.log" 2>&1
    [[ -f "$OUT_ROOT/experiments/$name/eval.json" ]] && return 0 || return 1
}

# Build the (year x test) cell list.
cells=()
for y in $YEARS; do for t in $TESTS; do cells+=("$y:$t"); done; done

mapfile -t GPUS < <(nvidia-smi -L 2>/dev/null | sed -E 's/GPU ([0-9]+):.*/\1/')
[[ ${#GPUS[@]} -eq 0 ]] && GPUS=(0)
free=()
for g in "${GPUS[@]}"; do for ((j = 0; j < JOBS_PER_GPU; j++)); do free+=("$g"); done; done

echo "run_families: ${#cells[@]} cells  years=[$YEARS]  tests=[$TESTS]"
echo "  out=$OUT_ROOT  GPUs=${GPUS[*]} x${JOBS_PER_GPU}"

declare -A pid_gpu=()
qi=0; n_ok=0; n_skip=0; n_fail=0; t0=$(date +%s)
while [[ $qi -lt ${#cells[@]} || ${#pid_gpu[@]} -gt 0 ]]; do
    while [[ ${#free[@]} -gt 0 && $qi -lt ${#cells[@]} ]]; do
        gpu="${free[0]}"; free=("${free[@]:1}")
        IFS=: read -r y t <<< "${cells[$qi]}"; qi=$((qi + 1))
        run_cell "$gpu" "$y" "$t" & pid_gpu[$!]="$gpu"
    done
    wait -n 2>/dev/null || true
    for pid in "${!pid_gpu[@]}"; do
        if ! kill -0 "$pid" 2>/dev/null; then
            wait "$pid" 2>/dev/null; rc=$?
            free+=("${pid_gpu[$pid]}"); unset 'pid_gpu[$pid]'
            case $rc in
                0) n_ok=$((n_ok + 1)) ;;
                2 | 3) n_skip=$((n_skip + 1)) ;;
                *) n_fail=$((n_fail + 1)) ;;
            esac
            echo "  [$((n_ok + n_skip + n_fail))/${#cells[@]}] ok=$n_ok skip=$n_skip fail=$n_fail ($(($(date +%s) - t0))s)"
        fi
    done
done
echo "RUN_FAMILIES_DONE ok=$n_ok skip=$n_skip fail=$n_fail out=$OUT_ROOT"
echo "Next: python analysis/leaderboard.py --experiments $OUT_ROOT/experiments"
