"""Variant-aware policy_battery: eval against N paraphrased variants per policy.

Parallel to evaluators/policy_battery.py but instead of scoring ONE question
per policy, scores N (typically 100) paraphrased variants generated by
scripts/data_prep/generate_question_variants.py. Reports mean ± std of
P(yes) and likert (centered, [-1, +1]) across the N variants per
(policy, year-model). The std is the reviewer-facing uncertainty band.

Reuses prompt builders and scoring helpers from policy_battery.py so the
single-question and variant-mean numbers are directly comparable.

Config keys (from experiment YAML eval section):
  source: "catalog" | "csv"
  catalog_path / csv_path / filter / modes: same as policy_battery
  variants_dir: path to data_artifacts/question_variants/  (default)
  variants_per_policy: cap N at runtime (default: use all variants on disk)

Outputs the usual eval.json shape under results.policies[] but with new fields:
  scores.yes_no.mean_p_yes, std_p_yes, p_yes_per_variant
  scores.likert5.mean_score, std_score, score_per_variant
  scores.likert5.mean_probs (averaged option-distributions)
"""
from __future__ import annotations

import json
import math
import time
from pathlib import Path
from typing import Any

# Import from sibling module. Works both as `policy_pred.evaluators.policy_battery_variants`
# (production via eval.py dispatcher) and as a standalone import for local testing.
try:
    from .policy_battery import (  # noqa: TID252
        EVALUATOR_VERSION as _PB_VERSION,
        LIKERT_OPTIONS,
        LIKERT_VALUES,
        YESNO_OPTIONS,
        _load_catalog,
        _load_csv,
        _apply_filter,
        _build_yesno_prompt,
        _build_likert_prompt,
    )
except ImportError:
    from policy_battery import (  # type: ignore[no-redef]
        EVALUATOR_VERSION as _PB_VERSION,
        LIKERT_OPTIONS,
        LIKERT_VALUES,
        YESNO_OPTIONS,
        _load_catalog,
        _load_csv,
        _apply_filter,
        _build_yesno_prompt,
        _build_likert_prompt,
    )


EVALUATOR_VERSION = f"variants-v1.0+pb={_PB_VERSION}"


# ---------------------------------------------------------------------------
# Variant loading
# ---------------------------------------------------------------------------

def _load_variants_for(event_id: str, variants_dir: Path) -> list[str]:
    """Load all variant questions for one policy. Returns list of question strings."""
    path = variants_dir / f"{event_id}.jsonl"
    if not path.exists():
        return []
    variants: list[str] = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            rec = json.loads(line)
            q = rec.get("variant_question")
            if isinstance(q, str) and q.strip():
                variants.append(q.strip())
    return variants


# ---------------------------------------------------------------------------
# Per-variant scoring helpers — call into policy_battery's prompt builders
# but inline the math so we can collect per-variant arrays cleanly.
# ---------------------------------------------------------------------------

def _score_yesno_variants(backend, variants: list[str]) -> dict:
    p_yes_list: list[float] = []
    logp_yes_list: list[float] = []
    logp_no_list: list[float] = []
    for q in variants:
        prompt = _build_yesno_prompt(q)
        scores = backend.score_continuations(prompt, YESNO_OPTIONS)
        logp_yes, logp_no = scores
        m = max(logp_yes, logp_no)
        p_yes_exp = math.exp(logp_yes - m)
        p_no_exp = math.exp(logp_no - m)
        p_yes = p_yes_exp / (p_yes_exp + p_no_exp)
        p_yes_list.append(p_yes)
        logp_yes_list.append(logp_yes)
        logp_no_list.append(logp_no)
    n = len(p_yes_list)
    if n == 0:
        return {"n_variants": 0}
    mean = sum(p_yes_list) / n
    std = (sum((x - mean) ** 2 for x in p_yes_list) / n) ** 0.5 if n > 1 else 0.0
    return {
        "n_variants": n,
        "mean_p_yes": mean,
        "std_p_yes": std,
        "p_yes_per_variant": p_yes_list,
        "logp_yes_per_variant": logp_yes_list,
        "logp_no_per_variant": logp_no_list,
    }


def _score_likert_variants(backend, variants: list[str]) -> dict:
    score_list: list[float] = []
    probs_list: list[list[float]] = []
    logp_list: list[list[float]] = []
    for q in variants:
        prompt = _build_likert_prompt(q)
        scores = backend.score_continuations(prompt, LIKERT_OPTIONS)
        m = max(scores)
        exps = [math.exp(s - m) for s in scores]
        total = sum(exps)
        probs = [e / total for e in exps]
        weighted = sum(p * v for p, v in zip(probs, LIKERT_VALUES))
        score_list.append(weighted)
        probs_list.append(probs)
        logp_list.append(list(scores))
    n = len(score_list)
    if n == 0:
        return {"n_variants": 0}
    mean = sum(score_list) / n
    std = (sum((x - mean) ** 2 for x in score_list) / n) ** 0.5 if n > 1 else 0.0
    # Average per-option probability across variants for an aggregate distribution.
    n_opts = len(LIKERT_OPTIONS)
    mean_probs = [sum(p[i] for p in probs_list) / n for i in range(n_opts)]
    return {
        "n_variants": n,
        "mean_score": mean,
        "std_score": std,
        "score_per_variant": score_list,
        "mean_probs": dict(zip([o.strip() for o in LIKERT_OPTIONS], mean_probs)),
        "probs_per_variant": probs_list,
        "logp_per_variant": logp_list,
    }


# ---------------------------------------------------------------------------
# Public entry point (called by eval.py dispatcher)
# ---------------------------------------------------------------------------

def run(backend, cfg: dict) -> dict:
    """Run the variant-aware policy battery. Returns a dict for eval.json."""
    source = cfg.get("source", "catalog")
    if source == "catalog":
        path = Path(cfg.get("catalog_path") or
                    Path(__file__).parent / "catalog.yaml")
        policies = _load_catalog(path)
    elif source == "csv":
        path = Path(cfg.get("csv_path") or "us_policy_event_battery_v4.csv")
        policies = _load_csv(path)
    else:
        raise ValueError(f"unknown source: {source!r} (expected 'catalog' or 'csv')")

    print(f"  loaded {len(policies)} policies from {path}")

    policies = _apply_filter(policies, cfg.get("filter") or {})
    if not policies:
        raise ValueError(f"no policies survived filter: {cfg.get('filter')}")
    print(f"  after filter: {len(policies)} policies")

    variants_dir = Path(cfg.get("variants_dir") or "data_artifacts/question_variants")
    if not variants_dir.exists():
        raise FileNotFoundError(
            f"variants_dir not found: {variants_dir}. "
            f"Run scripts/data_prep/generate_question_variants.py first."
        )
    cap = cfg.get("variants_per_policy")
    modes = cfg.get("modes") or ["yes_no", "likert5"]
    print(f"  variants_dir: {variants_dir}")
    print(f"  modes: {modes}")

    results: list[dict] = []
    for policy in policies:
        t0 = time.time()
        variants = _load_variants_for(policy["id"], variants_dir)
        if cap is not None:
            variants = variants[: int(cap)]
        if not variants:
            print(f"  {policy['id']:<32s}  NO VARIANTS — skipping")
            continue

        scores: dict[str, Any] = {}
        if "yes_no" in modes:
            scores["yes_no"] = _score_yesno_variants(backend, variants)
        if "likert5" in modes:
            scores["likert5"] = _score_likert_variants(backend, variants)

        # One-line summary per policy.
        summary = f"  {policy['id']:<32s}  n={len(variants):>3d}"
        if "yes_no" in scores:
            summary += (f"  P(yes)={scores['yes_no']['mean_p_yes']:.3f}"
                        f"±{scores['yes_no']['std_p_yes']:.3f}")
        if "likert5" in scores:
            summary += (f"  likert={scores['likert5']['mean_score']:+.3f}"
                        f"±{scores['likert5']['std_score']:.3f}")
        print(summary)

        results.append({
            "id": policy["id"],
            "implementation_year": policy.get("implementation_year"),
            "anticipation_start_year": policy.get("anticipation_start_year"),
            "description": policy.get("description"),
            "canonical_question": policy.get("question"),
            "n_variants_used": len(variants),
            "scores": scores,
            "elapsed_sec": time.time() - t0,
        })

    return {
        "evaluator": "policy_battery_variants",
        "evaluator_version": EVALUATOR_VERSION,
        "source": source,
        "n_policies": len(results),
        "modes": modes,
        "variants_dir": str(variants_dir),
        "policies": results,
    }
