"""Variant-aware policy_battery: eval against N paraphrased variants per policy.

Parallel to evaluators/policy_battery.py but instead of scoring ONE question
per policy, scores N (typically 100) paraphrased variants generated by
scripts/data_prep/generate_question_variants.py. Reports mean ± std of
P(yes) and likert (centered, [-1, +1]) across the N variants per
(policy, year-model). The std is the reviewer-facing uncertainty band.

Reuses prompt builders and scoring helpers from policy_battery.py so the
single-question and variant-mean numbers are directly comparable.

Config keys (from experiment YAML eval section):
  source: "catalog" | "csv"
  catalog_path / csv_path / filter / modes: same as policy_battery
  variants_dir: path to data_artifacts/question_variants/  (default)
  variants_per_policy: cap N at runtime (default: use all variants on disk)

Outputs the usual eval.json shape under results.policies[] but with new fields:
  scores.yes_no.mean_p_yes, std_p_yes, p_yes_per_variant
  scores.likert5.mean_score, std_score, score_per_variant
  scores.likert5.mean_probs (averaged option-distributions)
"""
from __future__ import annotations

import json
import math
import time
from pathlib import Path
from typing import Any

# Import from sibling module. Works both as `policy_pred.evaluators.policy_battery_variants`
# (production via eval.py dispatcher) and as a standalone import for local testing.
try:
    from .policy_battery import (  # noqa: TID252
        EVALUATOR_VERSION as _PB_VERSION,
        LIKERT_OPTIONS,
        LIKERT_VALUES,
        YESNO_OPTIONS,
        ANSWER_MARKER,
        _load_catalog,
        _load_csv,
        _apply_filter,
        _build_yesno_prompt,
        _build_likert_prompt,
        chat_prompt,
        build_yesno_cot_user,
        build_likert_cot_user,
    )
except ImportError:
    from policy_battery import (  # type: ignore[no-redef]
        EVALUATOR_VERSION as _PB_VERSION,
        LIKERT_OPTIONS,
        LIKERT_VALUES,
        YESNO_OPTIONS,
        ANSWER_MARKER,
        _load_catalog,
        _load_csv,
        _apply_filter,
        _build_yesno_prompt,
        _build_likert_prompt,
        chat_prompt,
        build_yesno_cot_user,
        build_likert_cot_user,
    )


EVALUATOR_VERSION = f"variants-v1.0+pb={_PB_VERSION}"


# ---------------------------------------------------------------------------
# Variant loading
# ---------------------------------------------------------------------------

def _load_variants_for(event_id: str, variants_dir: Path) -> list[str]:
    """Load all variant questions for one policy. Returns list of question strings."""
    path = variants_dir / f"{event_id}.jsonl"
    if not path.exists():
        return []
    variants: list[str] = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            rec = json.loads(line)
            q = rec.get("variant_question")
            if isinstance(q, str) and q.strip():
                variants.append(q.strip())
    return variants


# ---------------------------------------------------------------------------
# Per-variant scoring helpers — call into policy_battery's prompt builders
# but inline the math so we can collect per-variant arrays cleanly.
# ---------------------------------------------------------------------------

def _yesno_from_logps(logp_yes: float, logp_no: float) -> float:
    m = max(logp_yes, logp_no)
    a, b = math.exp(logp_yes - m), math.exp(logp_no - m)
    return a / (a + b)


def _aggregate_yesno(p_yes_list, logp_yes_list, logp_no_list, extra=None) -> dict:
    n = len(p_yes_list)
    if n == 0:
        return {"n_variants": 0}
    mean = sum(p_yes_list) / n
    std = (sum((x - mean) ** 2 for x in p_yes_list) / n) ** 0.5 if n > 1 else 0.0
    out = {"n_variants": n, "mean_p_yes": mean, "std_p_yes": std,
           "p_yes_per_variant": p_yes_list, "logp_yes_per_variant": logp_yes_list,
           "logp_no_per_variant": logp_no_list}
    if extra:
        out.update(extra)
    return out


def _aggregate_likert(score_list, probs_list, logp_list, extra=None) -> dict:
    n = len(score_list)
    if n == 0:
        return {"n_variants": 0}
    mean = sum(score_list) / n
    std = (sum((x - mean) ** 2 for x in score_list) / n) ** 0.5 if n > 1 else 0.0
    n_opts = len(LIKERT_OPTIONS)
    mean_probs = [sum(p[i] for p in probs_list) / n for i in range(n_opts)]
    out = {"n_variants": n, "mean_score": mean, "std_score": std,
           "score_per_variant": score_list,
           "mean_probs": dict(zip([o.strip() for o in LIKERT_OPTIONS], mean_probs)),
           "probs_per_variant": probs_list, "logp_per_variant": logp_list}
    if extra:
        out.update(extra)
    return out


def _likert_from_scores(scores: list[float]) -> tuple[float, list[float]]:
    m = max(scores)
    exps = [math.exp(s - m) for s in scores]
    total = sum(exps)
    probs = [e / total for e in exps]
    return sum(p * v for p, v in zip(probs, LIKERT_VALUES)), probs


def _score_yesno_variants(backend, variants: list[str], *, chat_format: bool = False) -> dict:
    """Direct Yes/No probe. chat_format wraps the prompt in 'User:…\\n\\nAssistant:'
    so the eval context matches how an SFT model was trained (vs bare for LoRA-only)."""
    p_yes_list, logp_yes_list, logp_no_list = [], [], []
    for q in variants:
        prompt = _build_yesno_prompt(q)
        if chat_format:
            prompt = chat_prompt(prompt)
        logp_yes, logp_no = backend.score_continuations(prompt, YESNO_OPTIONS)
        p_yes_list.append(_yesno_from_logps(logp_yes, logp_no))
        logp_yes_list.append(logp_yes)
        logp_no_list.append(logp_no)
    return _aggregate_yesno(p_yes_list, logp_yes_list, logp_no_list)


def _score_likert_variants(backend, variants: list[str], *, chat_format: bool = False) -> dict:
    score_list, probs_list, logp_list = [], [], []
    for q in variants:
        prompt = _build_likert_prompt(q)
        if chat_format:
            prompt = chat_prompt(prompt)
        scores = backend.score_continuations(prompt, LIKERT_OPTIONS)
        weighted, probs = _likert_from_scores(scores)
        score_list.append(weighted)
        probs_list.append(probs)
        logp_list.append(list(scores))
    return _aggregate_likert(score_list, probs_list, logp_list)


# --- CoT scorers: generate the model's reasoning, THEN score the answer ---

def _generate_reasoning(backend, gen_prompt: str, max_new_tokens: int) -> tuple[str, str]:
    """Generate reasoning from gen_prompt, stopping at the answer marker.

    Returns (reasoning_text_for_display, scoring_suffix) where scoring_suffix is
    the generated reasoning truncated to end exactly at ANSWER_MARKER, so
    score_continuations(gen_prompt + scoring_suffix, OPTIONS) reads the answer
    at the position the CoT-SFT trained for. If the model never emits the marker
    within the budget, we append it so a score is still defined.
    """
    gen = backend.generate(gen_prompt, max_new_tokens=max_new_tokens,
                           stop_sequences=[ANSWER_MARKER])
    idx = gen.find(ANSWER_MARKER)
    if idx == -1:
        suffix = gen.rstrip() + "\n\n" + ANSWER_MARKER
    else:
        suffix = gen[:idx + len(ANSWER_MARKER)]
    return gen, suffix


def _score_yesno_cot_variants(backend, variants: list[str], *, max_new_tokens: int = 256) -> dict:
    p_yes_list, logp_yes_list, logp_no_list, reasonings = [], [], [], []
    for q in variants:
        gen_prompt = chat_prompt(build_yesno_cot_user(q))
        reasoning, suffix = _generate_reasoning(backend, gen_prompt, max_new_tokens)
        logp_yes, logp_no = backend.score_continuations(gen_prompt + suffix, YESNO_OPTIONS)
        p_yes_list.append(_yesno_from_logps(logp_yes, logp_no))
        logp_yes_list.append(logp_yes)
        logp_no_list.append(logp_no)
        reasonings.append(reasoning)
    return _aggregate_yesno(p_yes_list, logp_yes_list, logp_no_list,
                            extra={"reasoning_per_variant": reasonings})


def _score_likert_cot_variants(backend, variants: list[str], *, max_new_tokens: int = 256) -> dict:
    score_list, probs_list, logp_list, reasonings = [], [], [], []
    for q in variants:
        gen_prompt = chat_prompt(build_likert_cot_user(q))
        reasoning, suffix = _generate_reasoning(backend, gen_prompt, max_new_tokens)
        scores = backend.score_continuations(gen_prompt + suffix, LIKERT_OPTIONS)
        weighted, probs = _likert_from_scores(scores)
        score_list.append(weighted)
        probs_list.append(probs)
        logp_list.append(list(scores))
        reasonings.append(reasoning)
    return _aggregate_likert(score_list, probs_list, logp_list,
                             extra={"reasoning_per_variant": reasonings})


# ---------------------------------------------------------------------------
# Public entry point (called by eval.py dispatcher)
# ---------------------------------------------------------------------------

def run(backend, cfg: dict) -> dict:
    """Run the variant-aware policy battery. Returns a dict for eval.json."""
    source = cfg.get("source", "catalog")
    if source == "catalog":
        path = Path(cfg.get("catalog_path") or
                    Path(__file__).parent / "catalog.yaml")
        policies = _load_catalog(path)
    elif source == "csv":
        path = Path(cfg.get("csv_path") or "us_policy_event_battery_v4.csv")
        policies = _load_csv(path)
    else:
        raise ValueError(f"unknown source: {source!r} (expected 'catalog' or 'csv')")

    print(f"  loaded {len(policies)} policies from {path}")

    policies = _apply_filter(policies, cfg.get("filter") or {})

    # Window filter: restrict which policies this year-model probes by enactment
    # year E relative to the model year. Two modes:
    #   window_years (symmetric): |model_year - E| <= window_years -> lookback in
    #     [-w, +w], so every policy is scored both before AND after enactment
    #     (the n-shape). Round-2 default.
    #   rel_min/rel_max (asymmetric, in rel = model_year - E terms): keep policies
    #     with rel_min <= model_year - E <= rel_max. E.g. rel in [-10, +20] (10 yr
    #     before enactment .. 20 yr after) => E in [model_year-20, model_year+10].
    #     Takes precedence over window_years when given.
    #   lookback_years (legacy, asymmetric): model_year <= E <= model_year+lb,
    #     i.e. lookback in [-lb, 0] only. Round-1 YAMLs use this; kept for compat.
    window_years = cfg.get("window_years")
    lookback_years = cfg.get("lookback_years")
    rel_min = cfg.get("rel_min")
    rel_max = cfg.get("rel_max")
    if (window_years is not None or lookback_years is not None
            or rel_min is not None or rel_max is not None):
        import re as _re
        exp_name = cfg.get("_experiment_name", "")
        m = _re.search(r"_(\d{4})_", exp_name) or _re.search(r"(\d{4})", exp_name)
        if m:
            model_year = int(m.group(1))
            if rel_min is not None or rel_max is not None:
                rmin = int(rel_min) if rel_min is not None else -10
                rmax = int(rel_max) if rel_max is not None else 10
                lo = model_year - rmax  # most-past enactment (largest +rel)
                hi = model_year - rmin  # most-future enactment (largest -rel)
            elif window_years is not None:
                lo = model_year - int(window_years)
                hi = model_year + int(window_years)
            else:
                lo, hi = model_year, model_year + int(lookback_years)
            before = len(policies)
            policies = [p for p in policies
                        if lo <= int(p.get("implementation_year", -1)) <= hi]
            print(f"  window filter (model_year={model_year}, "
                  f"window=[{lo},{hi}]): {before} -> {len(policies)} policies")

    if not policies:
        print(f"  no policies in lookback window for this year-model; skipping")
        return {"experiment_name": cfg.get("_experiment_name"),
                "n_policies": 0, "policies": []}
    print(f"  after filter: {len(policies)} policies")

    variants_dir = Path(cfg.get("variants_dir") or "data_artifacts/question_variants")
    if not variants_dir.exists():
        raise FileNotFoundError(
            f"variants_dir not found: {variants_dir}. "
            f"Run scripts/data_prep/generate_question_variants.py first."
        )
    cap = cfg.get("variants_per_policy")
    modes = cfg.get("modes") or ["yes_no", "likert5"]
    # chat_format wraps direct-probe prompts in the User:/Assistant: rendering the
    # SFT models were trained on; leave False for the LoRA-only baseline. CoT modes
    # always use the chat rendering (they must, to match CoT-SFT training).
    chat_format = bool(cfg.get("chat_format", False))
    cot_max_new_tokens = int(cfg.get("cot_max_new_tokens", 256))
    print(f"  variants_dir: {variants_dir}")
    print(f"  modes: {modes}  chat_format: {chat_format}"
          + ("  (CoT generation is slow — variants capped)" if cap else ""))

    results: list[dict] = []
    for policy in policies:
        t0 = time.time()
        variants = _load_variants_for(policy["id"], variants_dir)
        if cap is not None:
            variants = variants[: int(cap)]
        if not variants:
            print(f"  {policy['id']:<32s}  NO VARIANTS — skipping")
            continue

        scores: dict[str, Any] = {}
        if "yes_no" in modes:
            scores["yes_no"] = _score_yesno_variants(backend, variants, chat_format=chat_format)
        if "likert5" in modes:
            scores["likert5"] = _score_likert_variants(backend, variants, chat_format=chat_format)
        if "yes_no_cot" in modes:
            scores["yes_no_cot"] = _score_yesno_cot_variants(
                backend, variants, max_new_tokens=cot_max_new_tokens)
        if "likert5_cot" in modes:
            scores["likert5_cot"] = _score_likert_cot_variants(
                backend, variants, max_new_tokens=cot_max_new_tokens)

        # One-line summary per policy.
        summary = f"  {policy['id']:<32s}  n={len(variants):>3d}"
        for k in ("yes_no", "yes_no_cot"):
            if k in scores and "mean_p_yes" in scores[k]:
                summary += f"  {k}_P(yes)={scores[k]['mean_p_yes']:.3f}"
        for k in ("likert5", "likert5_cot"):
            if k in scores and "mean_score" in scores[k]:
                summary += f"  {k}={scores[k]['mean_score']:+.3f}"
        print(summary)

        results.append({
            "id": policy["id"],
            "implementation_year": policy.get("implementation_year"),
            "anticipation_start_year": policy.get("anticipation_start_year"),
            "description": policy.get("description"),
            "canonical_question": policy.get("question"),
            "n_variants_used": len(variants),
            "scores": scores,
            "elapsed_sec": time.time() - t0,
        })

    return {
        "evaluator": "policy_battery_variants",
        "evaluator_version": EVALUATOR_VERSION,
        "source": source,
        "n_policies": len(results),
        "modes": modes,
        "variants_dir": str(variants_dir),
        "policies": results,
    }
